### ISSUE TITLE
Accessibility: Check and improve

### ISSUE THREAD

**Issue by pixelstrolch** [WPZOO/Penguin#29]
- [x] Make submenu links visible when focused via tab
- [x] Do tests using tab for reading order and with forms
- [x] Check machine-readable text for buttons (see [Controls](https://make.wordpress.org/themes/handbook/review/accessibility/required/#controls))
- [x] Arrow down icons use same id several times
- [x] [Headings](https://developer.wordpress.org/themes/functionality/accessibility/#headings)
- [x] [Images](https://developer.wordpress.org/themes/functionality/accessibility/#images)
- [x] [Skip Links](https://developer.wordpress.org/themes/functionality/accessibility/#skip-links)
- [x] [Links](https://developer.wordpress.org/themes/functionality/accessibility/#links)
  - [x] [Link Text](https://developer.wordpress.org/themes/functionality/accessibility/#link-text) – Solution as it is described in [Link Text](https://make.wordpress.org/themes/handbook/review/accessibility/required/#link-text)
  - [x] [Link Highlighting](https://developer.wordpress.org/themes/functionality/accessibility/#link-highlighting)
  - [x] [Link Underlining](https://developer.wordpress.org/themes/functionality/accessibility/#link-underlining)
- [x] [Forms](https://developer.wordpress.org/themes/functionality/accessibility/#forms)
  - [x] [Form Markup](https://developer.wordpress.org/themes/functionality/accessibility/#form-markup)
  - [x] [On Form Submission](https://developer.wordpress.org/themes/functionality/accessibility/#on-form-submission)
  - [x] [Single Input Forms](https://developer.wordpress.org/themes/functionality/accessibility/#single-input-forms)
- [x] [Title Attributes](https://developer.wordpress.org/themes/functionality/accessibility/#title-attributes)
- [x] [Readability](https://developer.wordpress.org/themes/functionality/accessibility/#readability)
- [x] [Color](https://developer.wordpress.org/themes/functionality/accessibility/#color)
- [x] [Contrasts](https://developer.wordpress.org/themes/functionality/accessibility/#contrasts) – in most cases ok. There are some not much important places where the contrast is low, e.g. copyright info
- [x] [jQuery & JavaScript](https://developer.wordpress.org/themes/functionality/accessibility/#jquery-javascript)
- [x] [Validation](https://developer.wordpress.org/themes/functionality/accessibility/#validation)
- [x] [Things to Avoid](https://developer.wordpress.org/themes/functionality/accessibility/#things-to-avoid)
  - [x] [Spawning New Windows or Tabs](https://developer.wordpress.org/themes/functionality/accessibility/#spawning-new-windows-or-tabs)
  - [x] [Autoplay & Animations](https://developer.wordpress.org/themes/functionality/accessibility/#autoplay-animations)
  - [x] [Tabindexing](https://developer.wordpress.org/themes/functionality/accessibility/#tabindexing)
  - [x] [Accesskeys](https://developer.wordpress.org/themes/functionality/accessibility/#accesskeys)

**Comment by grappler** [comment]
A11y review feedback.

### Keyboard Navigation
- Scroll to top button doesn't have a good focus styles.

### Controls
I'll have to check is display: none allowed on search for submit button. I'm pretty sure it's not:
"Verify that all forms have submit buttons. Can be hidden, but if so must be hidden using screen-reader-text correctly"

### Skip links
- Pass

### Forms
- Pass

### Headings
- Pass

### ARIA Landmark Roles
- Add aria-label to navigations, this is helpful when there are several same roles on the page.
- See example https://make.wordpress.org/themes/handbook/review/accessibility/required/#aria-landmark-roles

### Link Text
- Pass

### Contrasts
- Copyright text is too low contrast.

### Images
- Add aria-hidden="true" to back to top and menu toggle SVG icons. I think they are just decorative.

### Media
- Pass

### Screen Reader Text
- Pass
- You might want to add word-wrap: normal to .screen-reader-text class. https://github.com/Automattic/_s/blob/master/style.css#L655
